-- Table: public.LILA_USER

-- DROP TABLE IF EXISTS public."LILA_USER";

CREATE TABLE IF NOT EXISTS public."LILA_USER"
(
    "ID" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "NICK_NAME" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "USER_pkey" PRIMARY KEY ("ID"),
    CONSTRAINT "NICK_NAME" UNIQUE ("NICK_NAME")
        INCLUDE("NICK_NAME")
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."LILA_USER"
    OWNER to postgres;